# Generated by Django 5.1.7 on 2025-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЦЕна')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
